### ISSUE TITLE
Leethub v.3 for FireFox

### ISSUE THREAD

**Issue by viCodexm** [raphaelheinz/LeetHub-3.0#15]
It would be nice to have this extention on FireFox - based browsers.

**Comment by raphaelheinz** [comment]
Hi @viCodexm,
I agree that it is nice to support Firefox. Thank you for your request. I have already tried to install the plugin on Firefox, but have not yet been successful. It is not sufficient to publish the code in the Firefox Store. Instead, we need to change the internal code to remove Chrome related code and support Firefox. I think this will take some time, but I'm not sure because I haven't implemented any Firefox plugins yet...

Does someone in this community have experience in creating Firefox plugins? What is the effort to add support for Firefox?

**Comment by raphaelheinz** [comment]
I added this issue to "Roadmap" page in our wiki. For now, I am closing this issue as it is not critical..
