### ISSUE TITLE
Not working when using two languages with the same problem on Leetcode

### ISSUE THREAD

**Issue by hovanhoa** [raphaelheinz/LeetHub-3.0#18]
**Describe the bug**
I use Python to solve the problem first. After that, I used Golang to solve this problem on Leetcode but It's not working, or sometimes it worked. But I don't know why

**To Reproduce**
1. Submit a solution with Python
2. Submit a solution with Golang
3. Go to GitHub repo to check the commit

**Expected behavior**
A new commit with the Golang language

**Additional context**
Sometimes the extension does not working, then I have to submit it multiple times

**Comment by raphaelheinz** [comment]
Hi @hovanhoa,
thanks for submitting this issue.
I have tried to reproduce, but everything works OK on my side. When using multiple languages, two separate files are created in my GitHub repository. Could you please try again?

One limitation of this plugin that might have influence on this:
You have to wait 4 seconds after submitting the solution before entering new characters or switching editor. In this time your solution is pushed to GitHub. The website must not change its layout in this time interval. This is not ideal, but I haven't found a better solution so far.

**Comment by raphaelheinz** [comment]
After checking again, I think you are facing the issue described in my last comment. Sorry for the inconvenience that we have to wait 4 seconds until the spinner is finished. I had to increase the timer some weeks ago otherwise the commits would not have been pushed GitHub at all. But as I have said, after submitting we are not allowed to enter anything in the editor or switching language otherwise the spinner is infinite..

**Comment by hovanhoa** [comment]
Oh, I already tested this again and it worked with your suppose. Thank you for your support
