### ISSUE TITLE
Enhance LeetHub with Manual Sync Button and Status Messages for Reliable GitHub Repository Updates

### ISSUE THREAD

**Issue by pr-citrate** [raphaelheinz/LeetHub-3.0#19]
### Problem Statement
I've encountered an issue with the current LeetHub extension where code submissions on LeetCode do not consistently synchronize with my GitHub repository. This inconsistency requires me to refresh the tab and resubmit my solutions multiple times, which is inconvenient and disrupts my workflow.

### Proposed Solution
I suggest adding a manual button within the LeetHub extension that allows users to manually trigger an add/update operation for the LeetCode problem in their repository. This feature would provide more control over the synchronization process, ensuring that submissions are properly recorded in the GitHub repository without needing to repeat submissions.

### Alternative Solutions
In addition to the manual submission button, implementing status messages would significantly improve the user experience by providing immediate feedback. These messages could include notifications such as "Creating commit" or "Submission not recorded", giving users clarity on the action's outcome and whether further steps are necessary.

### Additional Context
This feature request stems from personal experiences and discussions with other users facing similar synchronization challenges. Enhancing the extension with these capabilities would streamline the coding practice and submission process, making LeetHub even more valuable for the coding community.

**Comment by raphaelheinz** [comment]
Hi @pr-citrate,
thanks for your feedback. 

Regarding your synchronize issue:
Its a known limitation of this plugin, but I have not found a better solution so far. I added a section in README. Please read commit (0cea185). Its important not to enter new characters into the editor for approx 4 seconds afters submitting the solution. If you take this into account, the sync should work reliable.

I agree that a button to synchronize manually would be helpful. However, I am not sure how easy we can implement it, because we need to access the last submission id. I can have a look into this but I am not sure when I have time.

**Comment by raphaelheinz** [comment]
A manual synchronization button has been added in #25. I have published V0.0.9 to Google Chrome store, it should be approved in the next few days. I will close this issue :)
